### ISSUE TITLE
Caption seems to be broken on Python 3.11.6 + 2.1.0+cu121

### ISSUE THREAD

**Issue by JPS-GER** [bash-j/mikey_nodes#11]
I get the following error with Python 3.11.6 + Torch 2.1.0+cu121 (also used by the latest ComfyUI Standalone version):

!!! Exception during processing !!!
Traceback (most recent call last):
  File "C:\Users\jpswi\ComfyUI_full\ComfyUI\execution.py", line 152, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jpswi\ComfyUI_full\ComfyUI\execution.py", line 82, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jpswi\ComfyUI_full\ComfyUI\execution.py", line 75, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jpswi\ComfyUI_full\ComfyUI\custom_nodes\mikey_nodes\mikey_nodes.py", line 2943, in caption
    wrapped_text_height = len(wrapped_lines) * font.getsize('A')[1]  # Estimate using height of letter 'A'
                                               ^^^^^^^^^^^^
AttributeError: 'FreeTypeFont' object has no attribute 'getsize'

**Comment by bash-j** [comment]
Hey, do you have a font file in the comfyui/fonts folder?

**Comment by gnadenlos** [comment]
No, I'm using a font in c:\windows\fonts. This worked before, until I updates Python and Torch:

![image](https://github.com/bash-j/mikey_nodes/assets/17389612/27f90855-0770-4e65-b751-f3eb85ab89ac)

**Comment by JPS-GER** [comment]
> Hey, do you have a font file in the comfyui/fonts folder?

Not in the ComfyUI folder, just in c:\windows\fonts - which was no problem until ComfyUI was updates to a newer version of Python and Torch a few days ago.

**Comment by bash-j** [comment]
Looks like it was an issue caused by the new Pillow version 10.

Can you please update mikey nodes and try again?

**Comment by JPS-GER** [comment]
Still happens after the update:

![image](https://github.com/bash-j/mikey_nodes/assets/142158778/2fac723b-1b53-4b4c-91e3-162a7eec1d59)

**Comment by bash-j** [comment]
What about now?

**Comment by JPS-GER** [comment]
![image](https://github.com/bash-j/mikey_nodes/assets/142158778/1ed5fc9b-c2eb-43a6-b168-39eba25669a6)

**Comment by bash-j** [comment]
Ok, hopefully this time it works. I also tweaked the positioning for multiple lines to stop the bottom row from being cut off.

If you get 'undefined' in the caption like I did, removing and re-adding the node fixed that issue.

**Comment by JPS-GER** [comment]
Thanks, it works again. But text gets still cut off in some cases:

![image](https://github.com/bash-j/mikey_nodes/assets/142158778/b594760d-dd8c-48ca-8423-1ce6fb466f92)
