### ISSUE TITLE
Error when selecting styles

### ISSUE THREAD

**Issue by pphoto808** [bash-j/mikey_nodes#18]
Error:
Error occurred when executing Style Conditioner Base Only:

'g'

File "/Volumes/Extreme Pro/ComfyUI/execution.py", line 155, in recursive_execute
output_data, output_ui = get_output_data(obj, input_data_all)
File "/Volumes/Extreme Pro/ComfyUI/execution.py", line 85, in get_output_data
return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
File "/Volumes/Extreme Pro/ComfyUI/execution.py", line 78, in map_node_over_list
results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
File "/Volumes/Extreme Pro/ComfyUI/custom_nodes/mikey_nodes/mikey_nodes.py", line 2376, in add_style
positive_cond_base_new = CLIPTextEncodeSDXL.encode(self, base_clip, 1024, 1024, 0, 0, 1024, 1024, pos_prompt, pos_prompt)[0]
File "/Volumes/Extreme Pro/ComfyUI/comfy_extras/nodes_clip_sdxl.py", line 44, in encode
if len(tokens["l"]) != len(tokens["g"]):

Running on Mac Studio M2 Ultra

Node was working last time I used it. "None" does not produce error. Only occurs when I select a style.

**Comment by bash-j** [comment]
Can you please share your workflow? I just tried and it's working for me.

**Comment by pphoto808** [comment]
[reginal prompt test.json](https://github.com/bash-j/mikey_nodes/files/14027078/reginal.prompt.test.json)

My suspicion is it's probably more MacOS related than something with the node(s). Especially if the workflow works for you. Select any style other than "none". 

Thanks

**Comment by bash-j** [comment]
Are you using a SD 1.5 model? I don't think that will work, because the node was made for SDXL which has two text encoders, where only the style prompt is sent to the second encoder.

**Comment by pphoto808** [comment]
Yup, that was it! Works perfectly with my SDXL workflow. Thanks
