### ISSUE TITLE
Resize for SDXL error

### ISSUE THREAD

**Issue by Alphyn-gunner** [bash-j/mikey_nodes#2]
Hey, your set of nodes sounds massively useful, especially I see myself using the resize node a lot.
Unfortunately, I get the following error when trying to use it. 
![image](https://github.com/bash-j/mikey_nodes/assets/34932866/468fb74d-b810-4256-9fd8-c5b3626cb6d6)

**Comment by bash-j** [comment]
Hay,

Thanks for bringing this to my attention. 

I just pushed a fix that should hopefully fix this issue for you. Can you please update and try again?

Cheers

**Comment by Alphyn-gunner** [comment]
Thank you for such a quick fix! It all works perfectly. It has just downscaled a 4k image to a perfect size.

**Comment by bash-j** [comment]
Glad to hear! Thanks again
