### ISSUE TITLE
Wildcards

### ISSUE THREAD

**Issue by Latentnaut** [bash-j/mikey_nodes#22]
Hello,

I would like to know how I could get **same** wildcard outcome when I used it twice or more times into the processor.

For example, let's say I use __animal__ in my prompt 3 times, how can I get the same result? Right now I get 3 random animals.

Thank you for this amazing pack 😉

**Comment by bash-j** [comment]
Hey, I just updated the wildcard syntax. You can now use ! to use the same position in the file, e.g. `__!wildcard__`

**Comment by Latentnaut** [comment]
Wow awesome! thank you again :)
