### ISSUE TITLE
Upscale Tile Calculator fixed rate numbers have changed.

### ISSUE THREAD

**Issue by Neytiri7** [bash-j/mikey_nodes#26]
Usually 512, 640, 768, 1024, 2048
There's a well-known proportion like this...

As I checked the node, 513, 641, 769, 1025, 2049
It's +1 like this.

Please check if it's a bug or a planning intention.

![image](https://github.com/bash-j/mikey_nodes/assets/139053327/0387f2a1-9126-4966-a057-fc357943cf7f)

**Comment by bash-j** [comment]
Not sure what is going on for you. It should be incrementing in steps of 8. That's how it's working for me. If you click the number to bring up the input, can you manually change it to 512?

![image](https://github.com/bash-j/mikey_nodes/assets/3195567/3fbad6d8-c7d6-46be-9ee4-42c165ec6d0a)

**Comment by Neytiri7** [comment]
When I used it in the past, it was expressed as a resolution ratio that is usually used, but when I changed the number, it was raised by +1.

However, if this is the planning intention, I will use it according to the planning intention.
