### ISSUE TITLE
Installation Problem

### ISSUE THREAD

**Issue by AIMusicExperiment** [bash-j/mikey_nodes#3]
I followed your instructions, and although this cloned correctly, it didn't install. I suspect that this is because I use a "portable version" of ComfyUI, with embedded python. Most developers include an install.py and a install.bat file that resolves this. I would love to use you nodes, but I can't. . . Thanks for any help you can offer.

**Comment by bash-j** [comment]
Hello, is the mikey_nodes folder in the custom_nodes folder?

For example with the portable version it should look something like this:
`C:\ComfyUI_windows_portable\ComfyUI\custom_nodes\mikey_nodes`

There is no need to install anything. I try to not include any packages that are not already included with comfyUI.

If the folder is in the right place and it's still not loading, could you please check the console to see if there were any errors while loading?
