### ISSUE TITLE
Multiple Wildcards

### ISSUE THREAD

**Issue by mattymatty** [bash-j/mikey_nodes#33]
Can you update wildcard to support multiple wildcards inside each other. For example { man {pants|shirt} | woman {dress|purse} }. ImpactWildcardPrompt does this but I like mikey_nodes better

**Comment by bash-j** [comment]
I have made changes to the wildcard processor to support nested wildcard. Can you please check it is working for you as expected?

**Comment by mattymatty** [comment]
It works perfectly thank you so much! Your node is terrific. It updates when the wildcard file updates without having to refresh the browser!

**Comment by bash-j** [comment]
Good to hear! Yes, it reads the file when the job is run, so you can add new or change existing files at any time.
