### ISSUE TITLE
Lora Syntax Processor

### ISSUE THREAD

**Issue by JHNewton** [bash-j/mikey_nodes#6]
This particular node is rather interesting for me.  Unfortunately, it seems to require a seed and there is no attachment or widget for entering a seed. 

Question for you - can this node also read wildcard files and pull loras out if they are in the wildcard file?  as an example: I want to create a wildcard file with various races (fantasy) and other attributes.  ie -  
{male|female}, <lora:RPGelf:1.3>,  __eye-color__, __hair-color__
{male|female}, <lora:RPGDwarf:1.3>, __eye-color__, __hair-color__, __facial hair__

You probably get the idea.

**Comment by bash-j** [comment]
Thank you for bringing that to my attention @JHNewton.

I have added the seed widget to the node. It's only required for the <random:0:1> syntax which you can add to the weight. e.g. <lora:lora_file:<random:0.5:1>> and it will add a random number for the lora weight.

For the wildcard you should use the wildcard and lora syntax processor node, which does support __wildcard__ syntax, and yes it should also load the lora if the line returned from the wildcard file contains lora syntax.

![image](https://github.com/bash-j/mikey_nodes/assets/3195567/1a10575b-25c1-44a8-ae27-d706dcfe144b)

**Comment by JHNewton** [comment]
Cool. Thanks

**Comment by JHNewton** [comment]
I take it that you don't parse YAML wildcard files.


Regards,
John Newton

Fotographixs <http://www.fotographixs.com>
Instagram <https://instagram.com/john.fotographixs/>
Facebook <https://www.facebook.com/profile.php?id=1240206692>

I don't think that I'll ever reach the stage when I will say, "This is what
I believe. Finished." What I believe is alive ... and open to growth.
                                          --Madeleine L'Engle

**Comment by bash-j** [comment]
I'm not familiar with wildcard yaml files. How do they work?

**Comment by JHNewton** [comment]
It works! But I have no real idea w
How or why. I know that Was doesn't like them. The ones I'm trying to
figure out look interesting. It sort of looks like a marriage between xml
and json. No tabs allowed, only spaces.
Just so you know, I haven't look at any code for 20 years now. Python is
completely new to me and I'm stumbling my way trying to learn it. When I
retired, xml was the hot thing. So you're dealing with a 75 year old noobe.

**Comment by bash-j** [comment]
All good :) All the wildcards I have used are just plain text files with a different prompt on each line. So curious how a yaml would improve on that.

**Comment by JHNewton** [comment]
Take a look at " Billions of characters" on CivitAI. I that is a pretty
heavy duty. Yaml wildcard example. I'm still puzzling my way through it.

BTW, I jury rigged a solution. I'll send  json when I get back on the
computer

**Comment by JHNewton** [comment]
Getting an error today after doing an update:
!!! Exception during processing !!!
Traceback (most recent call last):
  File "D:\ComfyUI_windows_portable\ComfyUI\execution.py", line 151, in
recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
  File "D:\ComfyUI_windows_portable\ComfyUI\execution.py", line 81, in
get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION,
allow_interrupt=True)
  File "D:\ComfyUI_windows_portable\ComfyUI\execution.py", line 74, in
map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
TypeError: WildcardAndLoraSyntaxProcessor.process() got an unexpected
keyword argument 'extra_pnginfo'


Regards,
John Newton

Fotographixs <http://www.fotographixs.com>
Instagram <https://instagram.com/john.fotographixs/>
Facebook <https://www.facebook.com/profile.php?id=1240206692>

I don't think that I'll ever reach the stage when I will say, "This is what
I believe. Finished." What I believe is alive ... and open to growth.
                                          --Madeleine L'Engle

**Comment by bash-j** [comment]
Sorry about that. Can you please try updating again?
