### ISSUE TITLE
Mikey Node interference with ComfyUI-Manager?

### ISSUE THREAD

**Issue by tusharbhutt** [bash-j/mikey_nodes#7]
The last few versions of Mikey Nodes remove the "Manager" button that ComfyUI-Manager puts on the menu, rendering it unsuable.  The error message ComfyUi throws is:

  File "C:\Applications\StableDiffusion\ComfyUI\ComfyUI\custom_nodes\mikey_nodes\mikey_nodes.py", line 2200, in INPUT_TYPES
    default_model = '4x-UltraSharp.pth' if '4x-UltraSharp.pth' in s.upscale_models else s.upscale_models[0]
IndexError: list index out of range

When I remove Mikey Nodes, the program launches correctly and the Manager is restored.  

Any thoughts?

**Comment by bash-j** [comment]
Thanks for reporting the issue. I have just modified the code slightly, hopefully it should be fixed now.

The sampler nodes I made require an upscale model, but I didn't account for no upscale models being found.

Please git pull to update. If you still have issues, please let me know. Thanks.

**Comment by run-Fyre** [comment]
> Thanks for reporting the issue. I have just modified the code slightly, hopefully it should be fixed now.
> 
> The sampler nodes I made require an upscale model, but I didn't account for no upscale models being found.
> 
> Please git pull to update. If you still have issues, please let me know. Thanks.

This does not appear to be fixed unfortunately
I have just installed mikey_nodes for the first time on a clean Comfy UI installation, and it HAS removed my Manager button

**Comment by bash-j** [comment]
@run-Fyre is there an error in the terminal related to my nodes? There should be if something is going on.

**Comment by tusharbhutt** [comment]
Seems to be working for me now, the "manager" button from ComfyUI-Manager shows and is functional

**Comment by bash-j** [comment]
Thanks for letting me know @tusharbhutt
